server:
  port: 8080

spring:
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.8:3306/runmin?useUnicode=true&characterEncoding=utf8
    username: root
    password: s123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

  # 异常捕获
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 开启驼峰
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lanceyi.webapi.model

# PageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  #打印SQL信息
  level:
    com.lanceyi.webapi.dao: debug
